export const testimonials = [
    {
        name: 'Rodio',
        position: 'User, Member',
        avatar: '/img/logos/mythical/mythical.png',
        quote: "Pretty good, easy to make themes and edit it's interface. I've been using their projects for half a month now, seems pretty good ❤️",
    },
    {
        name: 'Usslmulk',
        position: 'User, Member',
        avatar: '/img/logos/mythical/mythical.png',
        quote: 'I love it is better then the most client areas out there. Never had a problem with them and support is really fast and helpful.',
    },
    {
        name: 'Pringles',
        position: 'User, Member',
        avatar: '/img/logos/mythical/mythical.png',
        quote: 'Easy to Install and understandable Docs, nice look and feel. I love it ❤️',
    },
    {
        name: 'Daniel',
        position: 'User, Member',
        avatar: '/img/logos/mythical/mythical.png',
        quote: "Bought mcutils from him to use with my hosting which uses blueprint addons, well, it works, have a nice GUI except it somehow bricked my console. Asked the developer on discord, very nice person indeed. Responded in a timely manner. Reason for 4 star is it's not working for me at the moment as he said he tested all other blueprint theme just not my one. I hope he can fix it soon.",
    },
    {
        name: 'SpyHost',
        position: 'User, Member',
        avatar: '/img/logos/mythical/mythical.png',
        quote: 'MythicalDash is op',
    },
    {
        name: 'LukasDev',
        position: 'User, Member',
        avatar: '/img/logos/mythical/mythical.png',
        quote: "I love it, it's easy to use and looks great. I would recommend it to anyone who is looking for a client area.",
    },
    {
        name: 'KaiKai2',
        position: 'User, Member',
        avatar: '/img/logos/mythical/mythical.png',
        quote: 'I mean MythicalDash v3 is kinda basic but it works and it does the job as it should!',
    },
    {
        name: 'Gresakm',
        position: 'User, Member',
        avatar: '/img/logos/mythical/mythical.png',
        quote: 'definitely more efficient and friendly editor than the default one in Pterodactyl panel',
    },
    {
        name: 'Futuraura',
        position: 'User, Member',
        avatar: '/img/logos/mythical/mythical.png',
        quote: "CTRL + S doesn't work, but seems to be working, altough there's a better version of this plugin by The Quantum Development called Code Editor for Pterodactyl and it was released way earlier. But it does do it's job (except for the CTRL + S quick save) so 2 stars.",
    },
    {
        name: 'SuperEvilLuke',
        position: 'User, Member',
        avatar: '/img/logos/mythical/mythical.png',
        quote: 'good concept, easy to setup, however things that are logged are very limited.',
    },
    {
        name: 'Emory',
        position: 'User, Member',
        avatar: '/img/logos/mythical/mythical.png',
        quote: "I mean for the price. I'm pretty happy with it. It will help clients who are looking to do cool stuff and make it more convenient.",
    },
    {
        name: 'Galaxy OP',
        position: 'CEO, Blazars Cloud',
        avatar: '/img/logos/mythical/mythical.png',
        quote: "FeatherPanel redefined our hosting experience — it’s lightning fast, feather-light on resources, and astonishingly intuitive. You can tell it was built by people who understand hosting inside and out!",
    },
    {
        name: 'Blanco',
        position: 'Cloud Architect',
        avatar: '/img/logos/mythical/mythical.png',
        quote: "I’ve worked with all the panels out there, and nothing comes close to FeatherPanel's modern design and seamless performance. Deployment is effortless, and our clients love the user experience.",
    },
    {
        name: 'Adam',
        position: 'Founder, ONHost',
        avatar: '/img/logos/mythical/mythical.png',
        quote: "How am I only just finding this panel? It works perfectly and looks amazing. Finally, a dev who actually keeps things updated!",
    },
    {
        name: 'ChristiannX',
        position: 'Founder, MultyPlay & ScrifySystems',
        avatar: '/img/logos/mythical/mythical.png',
        quote: "We switched to FeatherPanel after months of frustration with other solutions. The migration was simple, support was stellar, and our server operations have never been smoother.",
    },
    {
        name: 'Alexutzerion5',
        position: 'Founder, RexSystems & Lethal Romania',
        avatar: '/img/logos/mythical/mythical.png',
        quote: "FeatherPanel brought robust features, modern security, and true reliability to our network. It’s the upgrade I wish we’d made years ago!",
    },
    {
        name: 'Th3Hunter',
        position: 'Founder, KingsDomain',
        avatar: '/img/logos/mythical/mythical.png',
        quote: "I was impressed with how light and responsive FeatherPanel is. Managing even large fleets of servers is a breeze it’s seriously next-gen.",
    },
];
