export const products = [
    {
        name: 'FeatherPanel',
        description: 'FeatherPanel is a modern and sleek alternative to Pterodactyl Panel.',
        image: 'https://featherpanel.com/demo/dashboard.png?height=600&width=1200',
        technologies: ['PhP', 'MySQL', 'Wings', 'TailWind'],
        fullDescription: 'FeatherPanel is a modern and sleek alternative to Pterodactyl Panel.',
        features: [ 'New Icons', 'New Design', 'Native Plugin System', 'Friendly Developer Experience', "Faster", "Smaller", "Open Source"],
        images: [
            'https://featherpanel.com/demo/dashboard.png?height=600&width=1200',
            'https://featherpanel.com/demo/server_console.png?height=400&width=600',
            'https://featherpanel.com/demo/file_manager.png?height=400&width=600',
            'https://featherpanel.com/demo/admin_dashboard.png?height=400&width=600'
        ],
        link: 'https://featherpanel.com',
        purchaseLink: 'https://featherpanel.com/pricing',
        purchasePrice: '0.00'
    },
    {
        name: 'MythicalDash Remastered',
        description: 'Open-Source Client Area for Pterodactyl Panel designed for free hosting providers.',
        image: '/img/mythicaldash.png',
        technologies: ['PhP', 'MySQL', 'Pterodactyl Panel API', 'Vuexy'],
        fullDescription: 'Open-Source ',
        features: [
            'Open-Source',
            'Free',
            'Highly Customizable',
            'Highly Secure',
            '3rd most used client area for pterodactyl panel as of 2024',
        ],
        images: ['/img/mythicaldash.png'],
        link: 'https://www.mythical.systems/docs/mythicaldash-v3/install',
        purchaseLink: '/docs',
        purchasePrice: '0.00',
        demoLink: 'https://mythicaldash-v3.mythical.systems',
    },
    {
        name: 'MythicalUI - Pterodactyl Admin Theme',
        description: 'Next generation admin theme for pterodactyl panel.',
        image: '/img/mythicaladmin.png',
        technologies: ['Pterodactyl Panel', 'Theme'],
        fullDescription:
            'Introducing the MythicalUI Theme, a revolutionary design crafted to transform your Pterodactyl Panel into a sleek, user-friendly, and feature-rich interface. Crafted with a clean, professional aesthetic, MythicalUI is highly intuitive, ensuring even first-time administrators can navigate the panel with ease.',
        features: ['Color Changes', 'Search Bar', 'Auto Allocations', 'New Icons', 'New Design', 'Blueprint'],
        images: ['/img/mythicaladmin.png'],
        purchaseLink: 'https://www.sourcexchange.net/products/mythicalui-pterodactyl-theme',
        purchasePrice: '6.00',
    },
    {
        name: 'Gamster.org - Minecraft Network',
        description: 'The ultimate Minecraft network with a wide range of game modes and features.',
        image: '/img/gamster.png',
        technologies: ['Cracked', 'BungeeCord', 'Minecraft'],
        fullDescription: '',
        features: ['Cracked', 'Wide Range of Game Modes', 'Wide Range of Features', 'Non Pay2Win'],
        images: ['/img/gamster.png'],
        demoLink: 'https://gamster.org',
    },
    {
        name: 'MythicalPics',
        description: 'A powerful and nice looking image hosting website for your favorite images with no ads!.',
        image: '/img/mythicalpics.png',
        technologies: ['PhP', 'MySQL', 'Tabler.IO'],
        fullDescription:
            'MythicalPics is a user-friendly image hosting platform that offers a seamless experience for uploading and sharing images without any advertisements.',
        features: ['No Ads', 'Free unlimited cloud storage', 'Highly Secure', 'Highly Customizable'],
        images: ['/img/mythicalpics.png'],
        demoLink: 'https://i.mythical.systems',
    },
    {
        name: 'MythicalAdmin V2',
        description: 'A powerful and nice looking image hosting website for your favorite images with no ads!.',
        image: '/img/mythicaladmin/1.png',
        images: [
            '/img/mythicaladmin/1.png',
            '/img/mythicaladmin/2.png',
            '/img/mythicaladmin/3.png',
            '/img/mythicaladmin/4.png',
            '/img/mythicaladmin/5.png',
            '/img/mythicaladmin/6.png',
            '/img/mythicaladmin/7.png',
            '/img/mythicaladmin/8.png',
            '/img/mythicaladmin/9.png',
            '/img/mythicaladmin/10.png',
        ],
        technologies: ['PhP', 'MySQL', 'Pterodactyl Panel API', 'TailWind'],
        fullDescription:
            'Introducing the MythicalUI Theme, a revolutionary design crafted to transform your Pterodactyl Panel into a sleek, user-friendly, and feature-rich interface. Crafted with a clean, professional aesthetic, MythicalUI is highly intuitive, ensuring even first-time administrators can navigate the panel with ease.',
        features: ['Color Changes', 'Search Bar', 'Auto Allocations', 'New Icons', 'New Design'],
        purchaseLink: 'https://builtbybit.com/resources/mythical-admin-v2.59417/',
        purchasePrice: '14.99',
    },
    {
        name: 'Minecraft Utils | Blueprint & Legacy',
        description: 'A collection of utilities and tools to enhance your Minecraft server management experience.',
        image: '/img/mcutils/0.png',
        images: [
            '/img/mcutils/1.png',
            '/img/mcutils/2.png',
            '/img/mcutils/3.png',
            '/img/mcutils/4.png',
            '/img/mcutils/5.png',
            '/img/mcutils/6.png',
            '/img/mcutils/7.png',
            '/img/mcutils/8.png',
            '/img/mcutils/9.png',
            '/img/mcutils/10.png',
        ],
        technologies: ['PhP', 'MySQL', 'Pterodactyl Panel', 'TailWind'],
        fullDescription:
            'Minecraft Utils (McUtils) is a versatile and feature-rich collection of utilities and tools designed to enhance your Minecraft server management experience. Whether you are an experienced server administrator or just starting out, McUtils provides all the essential tools you need in one convenient place.',
        features: [
            'Message Managment',
            'Player Counter',
            'Server Logs',
            'Minimessage',
            'Motd Builder',
            'Gradient Builder',
        ],
        purchaseLink: 'https://builtbybit.com/resources/minecraft-utils-blueprint-legacy.59420/',
        purchasePrice: '9.99',
    },
];
