export const products = [
    {
        name: 'MythicalDash V3',
        description: 'Open-Source Client Area for Pterodactyl Panel designed for free hosting providers.',
        image: '/img/mythicaldash.png',
        technologies: ['PhP', 'MySQL', 'Pterodactyl Panel API', 'Vuexy'],
        fullDescription: 'Open-Source ',
        features: [
            'Open-Source',
            'Free',
            'Highly Customizable',
            'Highly Secure',
            '3rd most used client area for pterodactyl panel as of 2024',
        ],
        images: ['/img/mythicaldash.png'],
        link: 'https://www.mythical.systems/docs/mythicaldash-v3/install',
        purchaseLink: '/docs',
        purchasePrice: '0.00',
        demoLink: 'https://mythicaldash.mythical.systems',
    },
    {
        name: 'MythicalClient',
        description: 'High-performance, scalable whmcs style client area for hosting big enterprise providers.',
        image: '/img/mythicalclient.png',
        technologies: ['VueJs', 'Distributed Systems', 'PhP', 'MySQL'],
        fullDescription:
            'MythicalClient is a high-performance, scalable client area for hosting big enterprise providers. It is designed to be highly customizable and scalable to meet the needs of any hosting provider. MythicalClient is built on a distributed system architecture that allows it to scale horizontally as needed. It is highly secure and reliable, with built-in redundancy and failover capabilities. MythicalClient is designed to be highly customizable, with a wide range of features and options that can be tailored to meet the needs of any hosting provider. It is built on modern technologies and frameworks, including Vue.js, PHP, and MySQL, and is designed to be easy to use and maintain. MythicalClient is the perfect solution for hosting big enterprise providers that need a high-performance, scalable client area that can meet the needs of their customers.',
        features: ['Highly Scalable', 'High Performance', 'Highly Customizable', 'Highly Secure', 'Highly Reliable'],
        images: ['/img/mythicalclient.png'],
        purchaseLink: 'https://mythicalclient.mythical.systems',
        purchasePrice: 'FROM 0.00',
        demoLink: 'https://framework.mythical.systems',
    },
    {
        name: 'MythicalHosting',
        description: 'High-performance, scalable hosting solutions for all your needs.',
        image: '/img/mythicalhosting.png',
        technologies: ['Hosting'],
        fullDescription:
            'MythicalHosting is a high-performance, scalable hosting solution that is designed to meet the needs of any website or application. With MythicalHosting, you get a reliable, high-performance hosting solution that is backed by a team of experts who are dedicated to providing you with the best possible service. MythicalHosting offers a wide range of features and options that are designed to meet the needs of any website or application, including 24/7 support, 98.8% uptime, high performance, unlimited bandwidth, daily backups, and 10Gb/s network connectivity. Whether you are hosting a small personal website or a large enterprise application, MythicalHosting has the solution for you.',
        features: [
            '24/7 Support',
            '98.8% Uptime',
            'High Performance',
            'Unlimited Bandwidth',
            'Daily Backups',
            '10Gb/s Network',
        ],
        images: ['/img/mythicalhosting.png'],
        purchaseLink: '/mythicalhosting',
        purchasePrice: 'FROM 1.00',
    },
    {
        name: 'MythicalUI - Pterodactyl Admin Theme',
        description: 'Next generation admin theme for pterodactyl panel.',
        image: '/img/mythicaladmin.png',
        technologies: ['Pterodactyl Panel', 'Theme'],
        fullDescription:
            'Introducing the MythicalUI Theme, a revolutionary design crafted to transform your Pterodactyl Panel into a sleek, user-friendly, and feature-rich interface. Crafted with a clean, professional aesthetic, MythicalUI is highly intuitive, ensuring even first-time administrators can navigate the panel with ease.',
        features: ['Color Changes', 'Search Bar', 'Auto Allocations', 'New Icons', 'New Design', 'Blueprint'],
        images: ['/img/mythicaladmin.png'],
        purchaseLink: 'https://www.sourcexchange.net/products/mythicalui-pterodactyl-theme',
        purchasePrice: '6.00',
    },
    {
        name: 'MythicalUI - Uptime Kuma 8 Theme Pack',
        description: 'Take your monitoring software to the next level! 🚀',
        image: '/img/mythicalstatus.png',
        technologies: ['UptimeKuma', 'Tailwind', 'CSS'],
        fullDescription:
            "Transform your Uptime Kuma status page with MythicalUI, a premium collection of color themes designed for style, readability, and a professional touch. Whether you're monitoring personal projects or running enterprise-level systems, these themes bring life to your dashboard with a sleek, modern design.",
        features: ['Color Changes', '8 Color Schemes', 'New Icons', 'Animations', 'Faster Load Times', 'New Design'],
        demoLink: 'https://status.mythical.systems',
        images: ['/img/mythicalstatus.png'],
        purchaseLink: 'https://www.sourcexchange.net/products/mythicalui-uptime-kuma-8-theme-pack',
        purchasePrice: '5.00',
    },
    {
        name: 'MythicalLogin',
        description: 'The solution for Minecraft and Discord integration.',
        image: '/img/myhticallogin.png',
        technologies: ['Java', 'Minecraft', 'PaperSpigot', 'Auth System'],
        fullDescription:
            "Full source code and compiled version of MythicalLogin, a powerful and easy-to-use authentication system for Minecraft servers. With MythicalLogin, you can easily integrate your Minecraft server with Discord, allowing players to link their Minecraft account to their Discord account for easy authentication and access to exclusive features. MythicalLogin is fully customizable and easy to set up, with detailed documentation and support available to help you get started. Whether you're running a small private server or a large public network, MythicalLogin is the perfect solution for secure, reliable authentication.",
        features: [
            'BungeeCord Only',
            'Discord Integration',
            'Easy Setup',
            'Discord Bot',
            'Customizable',
            'Full Source Code',
        ],
        images: ['/img/myhticallogin.png'],
        purchaseLink: 'https://www.sourcexchange.net/products/mythicallogin-full-srccompiled',
        purchasePrice: '5.00',
    },
    {
        name: 'PylexWatch',
        description:
            'A powerful and nice looking streaming website for your favorite movies and tv shows with no ads!.',
        image: '/img/pylexwatch.jpg',
        technologies: ['Java', 'React', 'VidSRC'],
        fullDescription:
            'A powerful and nice looking streaming website for your favorite movies and tv shows with no ads! And its fully open source with no strings attached!',
        features: ['No Ads', 'Open Source', 'Free', 'Highly Customizable', 'Highly Secure'],
        images: ['/img/pylexwatch.jpg'],
        demoLink: 'https://pylex.watch',
    },
    {
        name: 'Gamster.org - Minecraft Network',
        description: 'The ultimate Minecraft network with a wide range of game modes and features.',
        image: '/img/gamster.png',
        technologies: ['Cracked', 'BungeeCord', 'Minecraft'],
        fullDescription: '',
        features: ['Cracked', 'Wide Range of Game Modes', 'Wide Range of Features', 'Non Pay2Win'],
        images: ['/img/gamster.png'],
        demoLink: 'https://gamster.org',
    },
    {
        name: 'MythicalPics',
        description: 'A powerful and nice looking image hosting website for your favorite images with no ads!.',
        image: '/img/mythicalpics.png',
        technologies: ['PhP', 'MySQL', 'Tabler.IO'],
        fullDescription:
            'MythicalPics is a user-friendly image hosting platform that offers a seamless experience for uploading and sharing images without any advertisements.',
        features: ['No Ads', 'Free unlimited cloud storage', 'Highly Secure', 'Highly Customizable'],
        images: ['/img/mythicalpics.png'],
        demoLink: 'https://i.mythical.systems',
    },
    {
        name: 'MythicalAdmin V2',
        description: 'A powerful and nice looking image hosting website for your favorite images with no ads!.',
        image: '/img/mythicaladmin/1.png',
        images: [
            '/img/mythicaladmin/1.png',
            '/img/mythicaladmin/2.png',
            '/img/mythicaladmin/3.png',
            '/img/mythicaladmin/4.png',
            '/img/mythicaladmin/5.png',
            '/img/mythicaladmin/6.png',
            '/img/mythicaladmin/7.png',
            '/img/mythicaladmin/8.png',
            '/img/mythicaladmin/9.png',
            '/img/mythicaladmin/10.png',
        ],
        technologies: ['PhP', 'MySQL', 'Pterodactyl Panel API', 'TailWind'],
        fullDescription:
            'Introducing the MythicalUI Theme, a revolutionary design crafted to transform your Pterodactyl Panel into a sleek, user-friendly, and feature-rich interface. Crafted with a clean, professional aesthetic, MythicalUI is highly intuitive, ensuring even first-time administrators can navigate the panel with ease.',
        features: ['Color Changes', 'Search Bar', 'Auto Allocations', 'New Icons', 'New Design', 'Blueprint'],
        purchaseLink: 'https://www.sourcexchange.net/products/mythicalui-v2-pterodactyl-admin',
        purchasePrice: '14.99',
    },
    {
        name: "Minecraft Utils | Blueprint & Legacy",
        description: "A collection of utilities and tools to enhance your Minecraft server management experience.",
        image: "/img/mcutils/0.png",
        images: [
            "/img/mcutils/1.png",
            "/img/mcutils/2.png",
            "/img/mcutils/3.png",
            "/img/mcutils/4.png",
            "/img/mcutils/5.png",
            "/img/mcutils/6.png",
            "/img/mcutils/7.png",
            "/img/mcutils/8.png",
            "/img/mcutils/9.png",
            "/img/mcutils/10.png",
        ],
        technologies: ["PhP", "MySQL", "Pterodactyl Panel", "TailWind"],
        fullDescription: "Minecraft Utils (McUtils) is a versatile and feature-rich collection of utilities and tools designed to enhance your Minecraft server management experience. Whether you are an experienced server administrator or just starting out, McUtils provides all the essential tools you need in one convenient place.",
        features: ["Message Managment", "Player Counter", "Server Logs", "Minimessage", "Motd Builder", "Gradient Builder"],
        purchaseLink: "https://www.sourcexchange.net/products/mcutils",
        purchasePrice: "9.99",
    }
];
